#
# OpenCV Builder
#

FROM debian:buster as opencv-builder

RUN apt-get -qq update && apt-get -qq install --no-install-recommends -y \
  build-essential \
  ca-certificates \
  cmake \
  ffmpeg \
  git \
  libatlas-base-dev \
  libavcodec-dev \
  libavformat-dev \
  libglib2.0-dev \
  libjpeg-dev \
  libpng-dev \
  libswscale-dev \
  libtiff-dev \
  libv4l-dev \
  libx264-dev \
  libxvidcore-dev \
  pkg-config \
  python3 \
  python3-dev \
  python3-numpy \
  python3-pip \
 # TODO: have option to exclude this, for other platforms
 # VAAPI drivers for Intel hardware accel
 #libva-drm2 libva2 i965-va-driver vainfo \

# Build Python wheel
RUN cd /tmp \
  && git clone --branch=24 --depth=50 https://github.com/skvark/opencv-python \
  && cd opencv-python \
  && ENABLE_HEADLESS=1 python3 setup.py bdist_wheel


#
# Frigate App Builder
#

FROM debian:buster-slim as app

RUN apt-get -qq update && apt-get -qq install --no-install-recommends -y \
  ffmpeg \
  libavcodec58 \
  libavformat58 \
  libavutil56 \
  libglib2.0-dev \
  libjpeg62-turbo \
  libpng16-16 \
  libswscale5 \
  python3 \
  python3-numpy \
  python3-pip \
  python3-setuptools \
  python3-wheel \
  # Coral USB Python API Dependencies
  libc++1 \
  libc++abi1 \
  libgcc1 \
  libunwind8 \
  libusb-1.0-0 \
  python3-numpy \
  python3-pil \
  wget \
  # Frigate Dependencies
  python3-flask \
  python3-paho-mqtt \
  python3-yaml \
 && rm -rf /var/lib/apt/lists/* 

WORKDIR /tmp

# Install python-opencv
COPY --from=opencv-builder /tmp/opencv-python/dist/opencv_python_*.whl /tmp/
RUN pip3 install opencv_python_headless-4*

# Download and install EdgeTPU libraries for Coral
RUN wget https://dl.google.com/coral/edgetpu_api/edgetpu_api_latest.tar.gz -O edgetpu_api.tar.gz \
  && tar xzf edgetpu_api.tar.gz

WORKDIR /tmp/edgetpu_api

COPY scripts/install_edgetpu_api.sh install.sh
RUN /bin/bash install.sh

# Python 3.7 workaround
RUN cd /usr/local/lib/python3.7/dist-packages/edgetpu/swig/ \
  && cp _edgetpu_cpp_wrapper.cpython-36m-x86_64-linux-gnu.so _edgetpu_cpp_wrapper.cpython-37m-x86_64-linux-gnu.so

# symlink the model and labels
RUN wget https://dl.google.com/coral/canned_models/mobilenet_ssd_v2_coco_quant_postprocess_edgetpu.tflite -O /frozen_inference_graph.pb
RUN wget https://dl.google.com/coral/canned_models/coco_labels.txt -O /label_map.pbtext

# Minimize image size 
RUN apt-get autoremove -y \
  && apt-get autoclean -y \
  && rm -rf /tmp/*

WORKDIR /opt/frigate/
ADD frigate frigate/
COPY detect_objects.py .
COPY benchmark.py .

CMD ["python3", "-u", "detect_objects.py"]
